### ISSUE TITLE
写了个  docker-compose.yml ，但是代理环境变量不生效

### ISSUE THREAD

**Issue by WangShuXian6** [aurora-develop/free-gpt3.5-2api#11]
每次请求都返回 
```
please restart the program、change the IP address、use a proxy to try again
```

docker-compose.yml
```yml
version: '3.8'
services:
  free-gpt3.5-2api:
    image: ghcr.io/aurorax-neo/free-gpt3.5-2api
    container_name: free-gpt3.5-2api
    ports:
      - "9846:3040"
    environment:
      LOG_LEVEL: "info"
      LOG_PATH: ""
      BIND: "0.0.0.0"
      PORT: "3040"
      PROXY: "http://127.0.0.1:10809,http://127.0.0.1:10809"
      AUTHORIZATIONS: "123456"
      POOL_MAX_COUNT: "64"
      AUTH_ED: "600"
    restart: unless-stopped

```
![image](https://github.com/aurora-develop/free-gpt3.5-2api/assets/30850497/3d147aa5-b061-4b8b-a53f-d667248b9241)
